# Generated by Django 4.2 on 2024-08-07 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_payment"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
