# Generated by Django 4.2 on 2024-08-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0004_alter_lesson_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
